services:
  api-server:
    build: ./node-server-tv-owl
    ports:
      - "5000:5000"
    env_file:
      - ./node-server-tv-owl/.env
    environment:
      - PORT=5000
    networks:
      - backend
      
  transcoding-server:
    build: ./transcoding-server
    ports:
      - "5001:5001"
    env_file:
      - ./transcoding-server/.env
    environment:
      - PORT=5001
    networks:
      - backend

  completion-server:
    build: ./completion-handler-server
    ports:
      - "5002:5002"
    env_file:
      - ./completion-handler-server/.env
    environment:
      - PORT=5002
    networks:  
      - backend

networks:
  backend:
    driver: bridge
      
